### ISSUE TITLE
failing to convert TIFF to COG (from Gb to few Kb) for Vizgen MERFISH data

### ISSUE THREAD

**Issue by IrinaVKuznetsova** [chaichontat/samui#79]
Dear developers, 

I'd like to test Samui on our Vizgen MERFISH data, so I tried to convert TIFF to COG. Each TIFF file is around 2.5Gb. Unfortunately, no matter what scale I choose in the `loop image` command  TIFF file remains large (~40k Kb). This size is too large for Samui, which returns the error _“Maximum call stack size exceeded”_. I also tried to use `–quality` parameter, but the command failed to generate the output if this parameter is set to 20, anything above 20 generates a file of ~10,000Kb size, which is again too big for Samui.  Would you be able to help me with this issue? Please see below the command I used to compress tiff file:

```
FILE=path_to_Tiff
loopy image $FILE --scale 0.497e-6       ### generates a tiff file ~40k Kb
```
 
OR,
 
```
FILE=path_to_Tiff
loopy image $FILE --scale 0.497e-6 –quality 20    #### doesn’t generate result
```
 
OR,
 
```
FILE=path_to_Tiff
loopy image $FILE --scale 0.497e-6 –quality 40    ### generates a tiff file ~10k Kb
```
 
  
Thank you so much for your time, looking forward to hearing from you.
Regards, 
Irina

**Comment by chaichontat** [comment]
The issue was with our command line tool. We didn't update the logic in the command line tool to match the update in our Python API. It's now fixed with the latest commit. Please `git pull` and try the command again.
