### ISSUE TITLE
instructions on how to generate data for Vizgen MERFISH data

### ISSUE THREAD

**Issue by IrinaVKuznetsova** [chaichontat/samui#80]
Dear developers, 

Could you please provide more instructions on how to generate and explore data for Vizgen MERFISH data on Sumai web browser.

I managed to convert TIFF files to COG. I can upload the sample folder to the browser, but I cant explore genes on the image
Used `process_merfish.py` script to generate a folder with `sample.json;  X.tif, cell.json; cells.bin and cellCoordinates.csv` , but still unable to explore genes on the image none of selected genes are highlighted on the image (please see below). 
Thank you
 
![Test17March (1)](https://user-images.githubusercontent.com/37644569/225842667-6ca93364-7ffb-44cd-8779-554eb99f2e00.jpg)

**Comment by chaichontat** [comment]
Hi, could you send me the sample files via email? I'll need the cell by gene matrix, cell coordinates, and the coordinate transformation matrix.

From the image, the gene data was loaded correctly. My guess is that the transformation that aligns the cell and image coordinates or the image scale are off.
