### ISSUE TITLE
Incorrect coloring of categorical features

### ISSUE THREAD

**Issue by Nick-Eagles** [chaichontat/samui#84]
I have a `Sample` instance, and am adding a categorical feature to it with:
```{python}
this_sample.add_csv_feature(
    spe.obs[spe_disc_features], name = "Groups", coordName = "coords",
    dataType = "categorical"
)
```

The feature `DataFrame` looks like this:
```
>>> spe.obs[spe_disc_features]
                   path_groups
barcode                       
AAACAAGTATCTCCCA-1        none
AAACAATCTACTAGCA-1        none
AAACACCAATAACTGC-1        none
AAACAGAGCGACTCCT-1        none
AAACAGCTTTCAGAAG-1        none
...                        ...
TTGTTTCACATCCAGG-1        none
TTGTTTCATTAGTCTA-1        none
TTGTTTCCATACAACT-1        none
TTGTTTGTATTACACG-1        none
TTGTTTGTGTAAATTC-1        none

[4876 rows x 1 columns]
```

The `path_groups` is indeed categorical, and has instances of all 3 of its categories:
```
>>> spe.obs['path_groups']
barcode
AAACAAGTATCTCCCA-1    none
AAACAATCTACTAGCA-1    none
AAACACCAATAACTGC-1    none
AAACAGAGCGACTCCT-1    none
AAACAGCTTTCAGAAG-1    none
                      ... 
TTGTTTCACATCCAGG-1    none
TTGTTTCATTAGTCTA-1    none
TTGTTTCCATACAACT-1    none
TTGTTTGTATTACACG-1    none
TTGTTTGTGTAAATTC-1    none
Name: path_groups, Length: 4876, dtype: category
Categories (3, object): ['none', 'Ab', 'n_Ab']
```

Within the output folder created by `this_sample.write()`, `Groups.csv` appears to be correctly formed with the `id` and `path_groups` columns and their correct values. However, when dragging the full output folder into Samui, all spots have a single value `0`, which is reflected in the color legend (see screenshot).

<img width="497" alt="Screen Shot 2023-04-13 at 2 39 09 PM" src="https://user-images.githubusercontent.com/45461721/231853463-632954c9-6d0b-48c2-86a6-9901fbf0f19c.png">

This strikes me as a bug, but please let me know if I'm doing something incorrectly or you need more info.

Thanks,

-Nick

**Comment by chaichontat** [comment]
I traced the bug to a logic that somehow turns an array into all zero during a function return. Still looking.
