### ISSUE TITLE
Choosing default sample

### ISSUE THREAD

**Issue by Nick-Eagles** [chaichontat/samui#86]
Hello,

When sharing a dataset with Samui, it would be useful to be able to select a "default" sample (one that would show first when the webpage is loaded). To my understanding, only alphabetical ordering of the sample name controls sample order and therefore which sample is shown when the webpage loads. Does the python API support specifying a first sample, or are there other tricks I'm missing?

Best,

-Nick

**Comment by chaichontat** [comment]
Ordering can now be enforced through the sample orders in the URL. Resolved in e82a4f4.
