### ISSUE TITLE
Webpage loading delay

### ISSUE THREAD

**Issue by Nick-Eagles** [chaichontat/samui#87]
Hello,

We recently used Samui to share a [10-sample dataset](https://samuibrowser.com/from?url=visium-spg-ad.s3.amazonaws.com/&s=V10A27106_D1_Br3880_AD&s=V10A27004_A1_Br3874_control&s=V10A27004_D1_Br3880_AD&s=V10A27106_A1_Br3874_control&s=V10A27106_B1_Br3854_AD&s=V10A27106_C1_Br3873_AD&s=V10T31036_A1_Br3874_control&s=V10T31036_B1_Br3854_AD&s=V10T31036_C1_Br3873_AD&s=V10T31036_D1_Br3880_AD), and are getting unexpectedly poor performance (in particular, it takes about 3 minutes on my laptop upon entering the URL before I can interact with the app, with similar timing when switching samples).

I know that Samui's performance can be much better, even on [larger datasets](https://samuibrowser.com/from?url=data2.loopybrowser.com/spatialDLPFC/&s=Br2720_ant&s=Br2720_mid&s=Br2720_post&s=Br2743_ant&s=Br2743_mid&s=Br2743_post&s=Br3942_ant&s=Br3942_mid&s=Br3942_post&s=Br6423_ant&s=Br6423_mid&s=Br6423_post&s=Br6432_ant&s=Br6432_mid&s=Br6432_post&s=Br6471_ant&s=Br6471_mid&s=Br6471_post&s=Br6522_ant&s=Br6522_mid&s=Br6522_post&s=Br8325_ant&s=Br8325_mid&s=Br8325_post&s=Br8492_ant&s=Br8492_mid&s=Br8492_post&s=Br8667_ant&s=Br8667_mid&s=Br8667_post).

I've noticed the delay simply when locally hosting individual samples, so I suspect it's something with the samples and not, say, the bucket. It might be too large to share sample folders here, but I can maybe slack them if you want.

Best,

-Nick

**Comment by chaichontat** [comment]
You need to use the `add_chunked_feature` instead of `add_csv_feature` for large features, such as expression data. Without which, Samui has to download the entirety of the expression dataset before showing anything. It takes in the same dataframe format as `add_csv_feature`.

This is done automatically in the `run_spaceranger` function in the `process_visiumif.py` example script.

**Comment by chaichontat** [comment]
Example code, assuming you have an existing Sample with coordinates already.

```python
import pandas as pd
from loopy.sample import Sample

sample = Sample(
    path="/Users/chaichontat/Downloads/a",
)

data = pd.read_csv("/Users/chaichontat/Downloads/a/Genes.csv", index_col=0)
data.index = data.index.astype(str)
(
    sample
    .add_chunked_feature(data, name="Genes", coordName="coords", unit="Log counts", sparse=True)
    .write()
)
```
