### ISSUE TITLE
spot size customization

### ISSUE THREAD

**Issue by madhavitippani** [chaichontat/samui#93]
I have been using the `size`  variable in the `addcoords` function to customise the spot size. No matter what size I use the spot diameter is by default showing as 55 microns. I am not sure if this is a bug or if I have to use other settings. Please help.

**Comment by chaichontat** [comment]
Please check the `sample.json` file in the sample folder. You could directly change the `size` parameter under the `spotsParams` section.

**Comment by madhavitippani** [comment]
Thanks Richard, I figured that.
