### ISSUE TITLE
Possible to use higher resolution images?

### ISSUE THREAD

**Issue by gouinK** [chaichontat/samui#95]
Greetings, I am really enjoying this viewer, but was wondering if there is any way to use higher resolution images in the viewer? I have tried increasing the quality parameter from 90 to 95, 98, or 100, but it does not seem to make a significant difference as all of them have a clearly reduced resolution compared to my input tiff file. Thank you for your help and insight!

**Comment by chaichontat** [comment]
The issue is that Samui is setup to display 8-bit images. When you feed in typically 10-bit images from a microscope, there's 4-fold less intensity granularity to display hence the reduced resolution. I believe that it's possible to change the config. Let me look into it.

**Comment by gouinK** [comment]
Hi, just checking in to see if it is possible to support higher precision formats, e.g. 16-bit images? Thanks!

**Comment by chaichontat** [comment]
Implemented in [baa3df1](https://github.com/chaichontat/samui/commit/baa3df1ddc7f76e8139a43b4b186ed874c78c595) 🎉 

Now, if you pass in a 16-bit image, Samui will not automatically downsample to 8-bit.

**Comment by gouinK** [comment]
This works as expected, thank you so much for the update! The viewer itself isn't able to render large sample areas at this bit depth, but I am guessing that is the expected behavior given the size of the files.

**Comment by chaichontat** [comment]
Interesting, could you share a file for me to test out? My email is in my commit info. The viewer should be invariant with respect to initial file size.

**Comment by gouinK** [comment]
Hi, after some digging it turns out that, as you mentioned, no matter what the size of the original image set is, the outputs from anything past this commit are much slower in your viewer than outputs from previous commits. Looking into the actual images that get output from the two different commits, one thing that stands out to me is this "TileOffsets" parameter, which I am admittedly not very familiar with. I unfortunately am not at liberty to share these images publicly, but hopefully the below comparison shows all information that would be needed. To be clear, both of the outputs below were generated using the same starting raw image, the only difference was the commit checked out when running the loopy processing.

Example image output from earlier commit `c214df98c3a79a37f889d47c3e2e1631054472cd`:
```
BitsPerPixel = 8
DimensionOrder = XYCZT
IsInterleaved = false
IsRGB = false
LittleEndian = true
PixelType = uint8
Series 0 Name = test_old.tif
SizeC = 1
SizeT = 1
SizeX = 15232
SizeY = 12800
SizeZ = 1
BitsPerSample = 8
Compression = JPEG
ImageLength = 12800
ImageWidth = 15232
Location = /mnt/test_old.tif
MetaDataPhotometricInterpretation = Monochrome
MetaMorph = no
NumberOfChannels = 1
PhotometricInterpretation = BlackIsZero
PlanarConfiguration = Chunky
SampleFormat = unsigned integer
SamplesPerPixel = 1
TileByteCounts = 32484
TileLength = 256
TileOffsets = 24458
TileWidth = 256
```

Example image output from current commit `58799f9b07250d6d4d7f0479ccdc9d2e8509f586`:
```
BitsPerPixel = 8
DimensionOrder = XYCZT
IsInterleaved = false
IsRGB = false
LittleEndian = true
PixelType = uint8 
Series 0 Name = test_new.tif
SizeC = 1
SizeT = 1
SizeX = 15232
SizeY = 12800
SizeZ = 1
BitsPerSample = 8
Compression = JPEG
ImageLength = 12800
ImageWidth = 15232
Location = /mnt/test_new.tif
MetaDataPhotometricInterpretation = Monochrome
MetaMorph = no
NumberOfChannels = 1
PhotometricInterpretation = BlackIsZero
PlanarConfiguration = Chunky
SampleFormat = unsigned integer
SamplesPerPixel = 1
TileByteCounts = 32484
TileLength = 256
TileOffsets = 10222040
TileWidth = 256
```
